project:
  type: website
  output-dir: docs   # GitHub Actions builds and deploys this directory
  render:
    - index.qmd
    - research/index.qmd
    - teaching/index.qmd
    - art/index.qmd

website:
  title: "Hema Balarama"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Art"
        href: art/index.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: false
